//#FILE_REGION[ VG03.H ]BEG###################################//

//|---- F01 ------|////[ DOTADIW:DLL_FUNC_LIST ]//
//|---- F02 ------|////[ DOTADIW:DLL_FUNC_LOAD ]//
//|-----F03 ------|////[ DOTADIW:DLL_CALL_CAST ]//

//|-----F04 ------|////[ DOTADIW:DLL_STRUCTS   ]//
//|-----F05 ------|////[ DOTADIW:DLL_TYPEDEFS  ]//

//|-----F06 ------|////[ DOTADIW:DLL_PARG_LIST ]//
//|-----F07 ------|////[ DOTADIW:DLL_WRAP_BOIL ]//
//|-----F08 ------|////[ DOTADIW:DLL_WRAP_MAKE ]//
//|-----F09 ------|////[ DOTADIW:MAKE_A_WINDOW ]//
//|-----F10 ------|////[ DOTADIW:WIN_IN_THREAD ]//
    

int
VG03_Demo( void ){
    printf("[BEG:VG03_DEMO]\n");


    F10_Main();


    printf("[END:VG03_DEMO]\n");
    return( 0 );
}//[;]//


//#FILE_REGION[ VG03.H ]END###################################//